config/routes.rb
Rails.application.routes.draw do
  resources :plays, only: [:index, :create]
  resources :images, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'images#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	has_many_attached :uploads
	scope :random, ->(limit){ActiveStorage::Attachment.order("RANDOM()").limit(limit)}
end

app/models/play.rb
class Play < ApplicationRecord
	validates :count_value, presence: true
	validates :img, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def create
    @image  = Image.new(image_params)
    
    if @image.save
      redirect_to images_path
    else
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(uploads: [])
    end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]

  def index
    @plays  = Play.all
    @images = Image.random(10).map{|i|url_for(i)}
  end

  def create
    @play = Play.new(play_params)

    respond_to do |format|
      if @play.save
        format.html { redirect_to @play, notice: 'Play was successfully created.' }
        format.json { render json: {data:@play, html: (render_to_string :partial => 'plays/table_row.html.erb', :locals => {play:@play})},status: :created }
      else
        format.html { render :new }
        format.json { render json: @play.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_play
      @play = Play.find(params[:id])
    end

    def play_params
      params.require(:play).permit(:img,:count_value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image||Image.new, local: true, id:'form-image-create') do |form| %>
  <div class="actions">
    <div class="form-group">
      <%= form.file_field :uploads,id:'upload-file', multiple: true, class: "form-control", required:true %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

<br>
<br>

app/views/images/_image.html.erb
<% image.uploads.each do |upload| %>
	<% if upload.variable? %>
	  <%= image_tag upload.variant(resize: "100x100") %>
	<% elsif upload.previewable? %>
	  <%= image_tag upload.preview(resize: "100x100") %>
	<% end %>
<% end %>

app/views/images/index.html.erb
<div id='home-images'>
	<%= render @images %>
</div>
<hr>

<div >
  <%= render 'form', image: @image %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= token_tag nil %>
    <div class="site-wrapper">
      <div class="">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Demo</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="<%= 'active' if current_page?(images_path) %>"><%= link_to 'Images', images_path %></li>
                  <li class="<%= 'active' if current_page?(plays_path) %>"><%= link_to 'plays', plays_path %></li>
                </ul>
              </nav>
            </div>
          </div>
          <br>
          <br>
          <div class="inner cover">
            <%= yield %>
          </div>

        </div>

      </div>

    </div>
  </body>
</html>

app/views/plays/_table.html.erb
<% plays ||= [] %>

<table id='table-listing' class="table">
	<thead>
	 	<tr>
		  <th>Count Value</th>
		  <th>Img</th>
		</tr>
	</thead>
	<tbody>
		<% plays.each do |play| %>
			<%= render partial:'table_row', locals: {play:play} %>
		<% end %>
	</tbody>
</table>

app/views/plays/_table_row.html.erb
<tr>
  <td><%=play.count_value%></th>
  <td><img width="50" height="50" src="<%= play.img %>"></th>
</tr>

app/views/plays/index.html.erb
<div id='game-container'>
  <div class="row">
    <div class="col-md-6">
      <%= render partial: 'table', locals: {plays: @plays} %>
    </div>
    <div class="col-md-6">
      <h1 id='counter'></h1>
      <div id='images-urls' data-urls="<%= @images.join('|')%>"></div>
      <img src='' id='target-img' width="100" height="100" style="display:none;">
      <hr>
      <%= link_to 'Toggle Image', '', id:'capture', class:'btn btn-danger' %>
      <hr>
    </div>
  </div>
</div>

<script>

  document.addEventListener('DOMContentLoaded', function(){
    new Manager(); // found in manager.js
  });

</script>